### PR TITLE
Fix focus and selection issues

### PR DESCRIPTION
**Pull request by larskarlitski**
See individual commits.

Also bump the version, so that we can depend on it from cockpit.

### CODE REVIEW

**Comment by mvollmer** [comment]
Let's make this also a PR on https://github.com/chjj/term.js and add it to the list of PRs in the README.

**Review by mvollmer — DISMISSED** [review]
(comment to satisfy github)

**Comment by larskarlitski** [comment]
> Let's make this also a PR on https://github.com/chjj/term.js and add it to the list of PRs in the README.

That project is no longer maintained. The author says so in the project's current [README](https://github.com/chjj/term.js/blob/master/README.md) and suggests using xterm.js instead. I looked into that a while ago and found that it isn't CSP ready and requires quite modern browsers. They don't seem to accept patches for that, as they've rewritten it to use canvas. I felt that jumping on such a young code base was not a good fit—especially as they haven't released that version yet—and decided to do the couple of fixes we need in our fork of term.js.

Sorry, which list of PRs do you mean?

**Comment by mvollmer** [comment]
> Sorry, which list of PRs do you mean?

The one in our README, that we use to justify the fork.

**Comment by mvollmer** [comment]
> That project is no longer maintained.

Ahh, I see.

**Review by mvollmer — APPROVED** [review]

**Pull request merged**
